baseURL = "https://tplant.com.au/"
languageCode = "en-us"
title = "Thomas Plant"
googleAnalytics = ""

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

[params] # theme parameters
    author = "Thomas Plant" # Author's name.
    info = "Backend developer" # Author's job title or info.
    description = "Thomas Plant's developer portfolio" # Site description.
    keywords = "developer,personal,portfolio" # Site keywords.
    avatarurl = "images/avatar.png" # Contain the path of the optional avatar in the static folder.

    footercontent = "Enter a text here." # Add footer content
    fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
    fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/Pl4nty/"
[[params.social]]
    name = "StackOverflow"
    weight = 2
    url = "https://stackoverflow.com/users/9412514/thomas-plant"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/t-plant/"

# Menu links
[[menu.main]]
    name = "Portfolio"
    weight = 1
    url  = "portfolio"
[[menu.main]]
    name = "Résumé"
    weight = 2
    url  = "resume"
[[menu.main]]
    name = "Contact"
    weight = 3
    url = "contact"