baseURL = "https://tplant.com.au/"
languageCode = "en"
title = "Thomas Plant"
googleAnalytics = ""
theme = "hugo-coder"

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true

pygmentsstyle = "bw" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters
    author = "Thomas Plant" # Author's name.
    info = "Backend developer" # Author's job title or info.
    description = "Thomas Plant's developer portfolio" # Site description.
    keywords = "developer,personal,portfolio" # Site keywords.
    avatarurl = "img/avatar.png" # Contain the path of the optional avatar in the static folder.

	favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "" # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false
    math = false

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/Pl4nty/"
[[params.social]]
    name = "StackOverflow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 2
    url = "https://stackoverflow.com/users/9412514/thomas-plant"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/t-plant/"

# Menu links
[[menu.main]]
    name = "Portfolio"
    weight = 1
    url  = "/portfolio/"
[[menu.main]]
    name = "Résumé"
    weight = 2
    url  = "/resume/"
[[menu.main]]
    name = "Contact"
    weight = 3
    url = "/contact/"

[build]
  publish = "demo/public"
  command = "make prepare && hugo --source demo --baseURL $URL"

[context.production.environment]
  HUGO_VERSION = "0.49.2"

[context.deploy-preview]
  command = "make prepare && hugo --source demo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.49.2"